name: Save Workout Data

on:
  push:
    paths:
      - 'subsites/Chest/Barbell%20Bench/data.txt'  # Correct path with %20 for space

jobs:
  save-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write data to file
        run: echo "Data goes here" >> subsites/Chest/Barbell%20Bench/data.txt

      - name: Commit changes
        run: git commit -am "Update workout data"
      
      - name: Push changes
        run: git push
